"""AEGIS 계약 스키마 — 서버 · 시뮬레이터 · 엣지 · 프론트가 공유하는 단일 정의.

출처: `docs/AEGIS_API명세서.md` (SSOT)

**스키마는 여기에만 정의한다.** 서버·`sim/`·`edge/` 어디서도 재정의하지 않고
반드시 이 패키지를 import 해서 메시지를 만든다(CLAUDE.md 절대규칙 5).

| 모듈 | 대응 절 |
|---|---|
| `edge` | §2 엣지 → 서버 WebSocket `/ws/edge` |
| `mqtt` | §3 서버 ↔ ESP32 MQTT |
| `rest` | §1.4 오류 · §4 REST API |
| `policies` | §4.5 정책값 |
| `ws` | §5 서버 → 대시보드 WebSocket `/ws/dashboard` |
| `enums` | 상태·유형 열거형 |
"""

from ._base import Bbox, Homography, PointM, PointPx, SpecModel
from .edge import (
    CameraHealth,
    CandidateMsg,
    DetectedObject,
    DetectedPerson,
    DetectedVehicle,
    EdgeMessage,
    FrameMsg,
    HeartbeatMsg,
    NearbyVehicle,
    TrackLostMsg,
)
from .enums import (
    AlertState,
    CameraState,
    ChatRoute,
    ClipStatus,
    DistanceMethod,
    EventStatus,
    HelmetState,
    ObjectClass,
    Posture,
    SearchMode,
    TrackLostReason,
    ViolationType,
)
from .mqtt import ALERT_TOPIC, DEVICE_STATUS_TOPIC, AlertCommand, DeviceStatus
from .policies import Policies, PolicyPatch
from .rest import (
    BriefingRequest,
    BriefingResponse,
    CalibrationPoint,
    CalibrationRequest,
    CalibrationResponse,
    CameraStatus,
    ChatRequest,
    ChatResponse,
    ChatSource,
    CloudStatus,
    EdgeStatus,
    ErrorBody,
    ErrorCode,
    ErrorResponse,
    EventDetail,
    EventListQuery,
    EventListResponse,
    EventPatchRequest,
    EventSummary,
    ManualAlertRequest,
    McuStatus,
    MetricsDistributionQuery,
    MetricsRepeatQuery,
    MetricsSummary,
    MetricsTimeseriesQuery,
    MuteAlertRequest,
    NearbySnapshot,
    ReferencePerson,
    RegulationRef,
    SceneSearchFilters,
    SceneSearchItem,
    SceneSearchRequest,
    SceneSearchResponse,
    SimilarIncident,
    StorageStatus,
    SystemStatus,
    TimelineEntry,
    TimeSyncStatus,
    VehicleClass,
    VehicleClassPatch,
    WeeklyReportRequest,
    WeeklyReportResponse,
    Zone,
)
from .ws import (
    AnomalyMsg,
    DashboardMessage,
    EventCreatedMsg,
    EventUpdatedMsg,
    MetricMsg,
    OverlayMsg,
    OverlayNearby,
    OverlayObject,
    OverlayPerson,
    OverlayVehicle,
    SystemMsg,
)

__all__ = [
    "ALERT_TOPIC",
    "DEVICE_STATUS_TOPIC",
    "AlertCommand",
    "AlertState",
    "AnomalyMsg",
    "Bbox",
    "BriefingRequest",
    "BriefingResponse",
    "CalibrationPoint",
    "CalibrationRequest",
    "CalibrationResponse",
    "CameraHealth",
    "CameraState",
    "CameraStatus",
    "CandidateMsg",
    "ChatRequest",
    "ChatResponse",
    "ChatRoute",
    "ChatSource",
    "ClipStatus",
    "CloudStatus",
    "DashboardMessage",
    "DetectedObject",
    "DetectedPerson",
    "DetectedVehicle",
    "DeviceStatus",
    "DistanceMethod",
    "EdgeMessage",
    "EdgeStatus",
    "ErrorBody",
    "ErrorCode",
    "ErrorResponse",
    "EventCreatedMsg",
    "EventDetail",
    "EventListQuery",
    "EventListResponse",
    "EventPatchRequest",
    "EventStatus",
    "EventSummary",
    "EventUpdatedMsg",
    "FrameMsg",
    "HeartbeatMsg",
    "HelmetState",
    "Homography",
    "ManualAlertRequest",
    "McuStatus",
    "MetricMsg",
    "MetricsDistributionQuery",
    "MetricsRepeatQuery",
    "MetricsSummary",
    "MetricsTimeseriesQuery",
    "MuteAlertRequest",
    "NearbySnapshot",
    "NearbyVehicle",
    "ObjectClass",
    "OverlayMsg",
    "OverlayNearby",
    "OverlayObject",
    "OverlayPerson",
    "OverlayVehicle",
    "PointM",
    "PointPx",
    "Policies",
    "PolicyPatch",
    "Posture",
    "ReferencePerson",
    "RegulationRef",
    "SceneSearchFilters",
    "SceneSearchItem",
    "SceneSearchRequest",
    "SceneSearchResponse",
    "SearchMode",
    "SimilarIncident",
    "SpecModel",
    "StorageStatus",
    "SystemMsg",
    "SystemStatus",
    "TimeSyncStatus",
    "TimelineEntry",
    "TrackLostMsg",
    "TrackLostReason",
    "VehicleClass",
    "VehicleClassPatch",
    "ViolationType",
    "WeeklyReportRequest",
    "WeeklyReportResponse",
    "Zone",
]
